# Generated by Django 3.0.7 on 2020-11-02 17:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=30)),
                ('warning_event', models.ImageField(choices=[(1, 'Always'), (2, 'Raining tomorrow'), (3, 'Snowing tomorrow'), (4, 'Temperature dropping by 3 F ')], default=0, upload_to='')),
                ('reminder_sent', models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
