# Generated by Django 3.0.7 on 2020-11-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='warning_event',
            field=models.IntegerField(choices=[(1, 'Always'), (2, 'Raining tomorrow'), (3, 'Snowing tomorrow'), (4, 'Temperature dropping by 3 F ')], default=0),
        ),
    ]
