# Generated by Django 3.0.7 on 2020-11-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20201102_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='warning_event',
            field=models.IntegerField(default=0),
        ),
    ]
